spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:gymbook;MODE=MySQL
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    sql: info

api:
  get-holiday:
    base-url: ${HOLIDAY_API_URL}
    service-key: ${HOLIDAY_API_KEY}
